In [2]:
import numpy as np

In [6]:
A = np.array([
[2 , 3 , 7],
[8 , 9 , 1]]
)

B = np.array([
[1 , 3 , 0],
[2 , 4 , 1]
])

print(A + B)
print(2 * A)
print(A * B)
# Element wise multiplication
# print(A.dot(B))
# Error: incompatible dimensions
print(A.dot(B.T))
# Matrix multiplication

[[ 3  6  7]
 [10 13  2]]
[[ 4  6 14]
 [16 18  2]]
[[ 2  9  0]
 [16 36  1]]
[[11 23]
 [35 53]]
